---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
checks:
  method-complexity:
    enabled: false
  method-lines:
    config:
      threshold: 30
  argument-count:
    config:
      threshold: 5
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.py"
exclude_paths:
- cms/migrations/
- mainapp/migrations/
- mainapp/fixtures/
- manage.py
