---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
  fixme:
    enabled: true
  radon:
    enabled: true
    checks:
      Complexity:
        enabled: false
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.py"
exclude_paths:
- mainapp/migrations/
- mainapp/fixtures/
- mainapp/assets/vendored/
- manage.py
