language: python
python:
  - "3.5"
  - "3.5_with_system_site_packages"
  - "3.6"
  - "3.6_with_system_site_packages"

addons:
  apt:
    packages:
      - python3-gi

cache:
 - pip
 - apt

before_script:
 # Add pygobject to the virtualenv
 - ln -s /usr/lib/python3/dist-packages/gi $VIRTUAL_ENV/lib/*/site-packages/
 - cp etc/env-template .env

script:
  - ./manage.py migrate
  - ./manage.py test