language: python
dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"

addons:
  chrome: stable # Just to be sure
  apt:
    packages:
      - libmysqlclient-dev
      - libmagickwand-dev
      - poppler-utils
      - tesseract-ocr
      - libgirepository1.0-dev

cache:
  pip: true
  npm: true

install:
  - npm ci
  - pip install poetry --upgrade
  - poetry install
  # Add pygobject to the virtualenv; Disabled because gi only works with system python
  # - ln -s /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/gi $VIRTUAL_ENV/lib/*/site-packages/

script:
  # Ensure our migrations are working (squashing can cause weird problems)
  - ENV_PATH=etc/env-test poetry run python ./manage.py migrate
  - npm run build:prod
  - npm run build:dev
  - poetry run python ./manage.py test
