language: python
python:
  - "3.5"
  - "3.6"

env:
 - PIPENV_VENV_IN_PROJECT=True

cache:
 pip: true
 npm: true
 directories:
  - .venv

install:
 - npm install
 - pip install pipenv --upgrade
 - pipenv install --deploy
 # Add pygobject to the virtualenv
 # - ln -s /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/gi $VIRTUAL_ENV/lib/*/site-packages/

script:
  # Ensure our migrations are working (squashing can cause weird problems)
  - ENV_PATH=etc/env-test pipenv run ./manage.py migrate
  - npm run build:dev
  - npm run build:prod
  - pipenv run ./manage.py test
