addons:
  chrome: stable

language: python
python:
  - "3.5"
  - "3.6"

cache:
 - pip
 - npm

install:
 - npm install
 - pip install -r requirements.txt
 - wget -N http://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip -P ~/
 - unzip ~/chromedriver_linux64.zip -d ~/
 - rm ~/chromedriver_linux64.zip
 - sudo mv -f ~/chromedriver /usr/local/share/
 - sudo chmod +x /usr/local/share/chromedriver
 - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

before_script:
 # Add pygobject to the virtualenv
 # - ln -s /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/gi $VIRTUAL_ENV/lib/*/site-packages/
 - cp etc/env-template .env

script:
  - ./manage.py migrate
  - npm run build:dev
  - npm run build:prod
  - ./manage.py test --settings=meine_stadt_transparent.settings_test
