language: python
dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"

addons:
  chrome: stable # Just to be sure
  apt:
    packages:
      - libmysqlclient-dev
      - libmagickwand-dev
      - poppler-utils
      - tesseract-ocr

cache:
  pip: true
  npm: true

install:
  - npm ci
  - pip install poetry --upgrade
  - poetry install

script:
  # Ensure our migrations are working (squashing can cause weird problems)
  - ENV_PATH=etc/test.env poetry run python ./manage.py migrate
  - npm run build:prod
  - npm run build:dev
  - poetry run python ./manage.py test
