language: python
python:
  - "3.6"
  #- "3.7"

addons:
  chrome: stable # Just to be sure
  apt:
    packages:
      - libxml2-dev
      - libxslt1-dev
      - antiword
      - unrtf
      - poppler-utils
      - pstotext
      - tesseract-ocr
      - flac
      - libav-tools
      - lame
      - libmad0
      - libsox-fmt-mp3
      - sox
      - libjpeg-dev
      - swig
      - libpulse-dev

cache:
  pip: true
  npm: true
  apt: true

install:
  - npm install --ci
  - pip install poetry --upgrade
  - poetry install
  # Add pygobject to the virtualenv; Disabled because gi only works with system python
  # - ln -s /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/gi $VIRTUAL_ENV/lib/*/site-packages/

script:
  # Ensure our migrations are working (squashing can cause weird problems)
  - ENV_PATH=etc/env-test poetry run ./manage.py migrate
  - npm run build:dev
  - npm run build:prod
  - poetry run ./manage.py test
