language: python
python:
  - "3.5"
  - "3.6"

addons:
  chrome: stable

cache:
 - pip
 - npm

install:
 - npm install
 - pip install -r requirements.txt
 # Add pygobject to the virtualenv
 # - ln -s /usr/lib/python$TRAVIS_PYTHON_VERSION/dist-packages/gi $VIRTUAL_ENV/lib/*/site-packages/

script:
  - ENV_PATH=etc/env-test ./manage.py migrate
  - npm run build:dev
  - npm run build:prod
  - ENV_PATH=etc/env-test ./manage.py test
