version: '3'
services:
  django:
    build: .
    container_name: django
    volumes:
      - django_media:/media
      - django_static:/static
      - django_cache:/cache
      - "${DOKER_COMPOSE_ENV:-./etc/env-docker-compose}:/config/.env"
    ports:
      - ${DJANGO_PORT:-8000}:8000
    networks:
      - network
    depends_on:
      - mariadb
      - elasticsearch

  mariadb:
    image: mariadb:10
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=meinestadttransparent
      - MYSQL_USER=meinestadttransparent
      - MYSQL_PASSWORD=meinestadttransparent
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    networks:
      - network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false

    ulimits: # Elasticsearch needs those
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - network

volumes:
  django_media:
  django_static:
  django_cache:
  mariadb_data:
  elasticsearch_data:

networks:
  network:
