# This is need for our development workflow
# https://xkcd.com/1172/

version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.13
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits: # Elasticsearch needs those
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
        - 9300:9300
    networks:
      - mst_dev

  kibana:
      image: docker.elastic.co/kibana/kibana:5.6.13
      ports:
        - 5601:5601
      networks:
        - mst_dev
      environment:
        - xpack.security.enabled=false

  minio:
      image: minio/minio
      container_name: minio
      volumes:
        - minio_data:/minio_data
      environment:
        MINIO_ACCESS_KEY: meinestadttransparent
        MINIO_SECRET_KEY: meinestadttransparent
      ports:
        - 9000:9000
      networks:
        - mst_dev
      command: server /minio_data

volumes:
  elasticsearch_data:
  minio_data:

networks:
  mst_dev:
