# This is needed for our development workflow
# https://xkcd.com/1172/

version: '3'
services:
  elasticsearch-dev:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.5.0
    container_name: elasticsearch-dev
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits: # Elasticsearch needs those
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
        - 9300:9300
    networks:
      - mst_dev

  kibana-dev:
      image: docker.elastic.co/kibana/kibana-oss:7.5.0
      container_name: kibana-dev
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch-dev:9200
      ports:
        - 5601:5601
      networks:
        - mst_dev

  minio-dev:
      image: minio/minio
      container_name: minio-dev
      volumes:
        - minio_data:/minio_data
      environment:
        MINIO_ACCESS_KEY: meinestadttransparent
        MINIO_SECRET_KEY: meinestadttransparent
      ports:
        - 9000:9000
      networks:
        - mst_dev
      command: server /minio_data

volumes:
  elasticsearch_data:
  minio_data:

networks:
  mst_dev:
