version: '3'
services:
  kibana:
      image: docker.elastic.co/kibana/kibana:5.6.3
      ports:
        - 5601:5601
      networks:
        - meinestadttransparent_net
      environment:
        - xpack.security.enabled=false
