# This is need for our development workflow
# Use it as an extension to the elasticsearch.yml
# https://xkcd.com/1172/

version: '3'
services:
  kibana:
      image: docker.elastic.co/kibana/kibana:5.6.12
      ports:
        - 5601:5601
      networks:
        - meinestadttransparent_net
      environment:
        - xpack.security.enabled=false
