[tool.poetry]
name = "meine-stadt-transparent"
version = "0.2.0"
description = "A website to bring municipal politics to citizens"
authors = ["Tobias Hößl <tobias@hoessl.eu>", "Konstantin Schütze <konstin@mailbox.org>"]
license = "MIT"

[tool.poetry.dependencies]
Django = "~2.1"
django-allauth = "^0.38"
django-anymail = "^5.0"
django-braces = "^1.13"
django_csp = "^3.4"
django-debug-toolbar = "^1.9"
django-elasticsearch-dsl = "^0.5"
django-environ = "^0.4"
django-geojson = "^2.11"
django-settings-export = "^1.2"
django-simple-history = "^2.3"
django-webpack-loader = "^0.6"
django-widget-tweaks = "^1.4"
elasticsearch-dsl = "^5.4"
geoextract = "^0.3.1"
geopy = "^1.17"
gunicorn = "^19.9"
html2text = "^2018.1"
icalendar = "^4.0"
jsonfield = "^2.0"
mysqlclient = "^1.3"
pgpy = "^0.4.3"
PyPDF2 = "^1.26"
python = "^3.5"
python-slugify = "^1.2"
requests = "^2.19"
splinter = "^0.7"
Wand = "^0.4.4"
sentry-sdk = "^0.6.0"

[tool.poetry.dev-dependencies]
# See https://github.com/SeleniumHQ/selenium/issues/5296
selenium = "3.141.0"
tox = "^3.5"
# We can't directly depend on black here because then we'd need to require python 3.6 as minimum

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | \.tox
  | mainapp/migrations
  | node_modules
  | static
)/
'''
