version: '3'
services:
  django:
    image: konstin2/meine-stadt-transparent
    container_name: django
    volumes:
      - django_static:/static
      - ./.env:/app/.env
    ports:
      - 8000:8000
    networks:
      - mst_network

  mariadb:
    image: mariadb:10
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=meinestadttransparent
      - MYSQL_USER=meinestadttransparent
      - MYSQL_PASSWORD=changeme
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    networks:
      - mst_network
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.13
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits: # Elasticsearch needs those
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - mst_network

  minio:
      image: minio/minio
      container_name: minio
      volumes:
        - minio_data:/minio_data
      environment:
        MINIO_ACCESS_KEY: meinestadttransparent
        MINIO_SECRET_KEY: changeme
      ports:
        - 9000:9000
      networks:
        - mst_network
      command: server /minio_data

volumes:
  django_static:
    external: true
  mariadb_data:
  elasticsearch_data:
  minio_data:

networks:
  mst_network:
