name: oparl test publish

on:
  push:
    branches: [ 'master' ]
    tags: [ '*' ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          path: etc
          dockerfile: etc/Dockerfile.oparl-test
          username: konstin2
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: konstin2/mst-oparl-test
          tag_with_ref: true
