name: Docker build

on:
  push:
    branches: [ 'master' ]
    tags: [ '*' ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.0.1
        with:
          username: konstin2
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: konstin2/meine-stadt-transparent
          cache-from: konstin2/meine-stadt-transparent
          tag_with_ref: true
          build_args: BUILDKIT_INLINE_CACHE=1
